apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: app1
        image: mahendrshinde/myweb:latest
        ports:
        - containerPort: 80
