apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: testpod
spec:
  containers:
  - name: testpod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
