apiVersion: v1
kind: Service
metadata:
  name: sts-svc
spec:
  clusterIP: None
  selector:
    app: pv-pods-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pvc-deploy
spec:
  serviceName: sts-svc
  replicas: 2

  volumeClaimTemplates:
    - metadata:
        name : webdata
      spec:
        volumeMode: Filesystem
        accessModes:
            - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

  selector:
    matchLabels:
      app: pv-pods-sts
  template:
    metadata:
      labels:
        app: pv-pods-sts
    spec:  
      containers:
      - name: web
        image: mahendrshinde/myweb
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: webdata